# common settings for repo_usd for all USD plug-ins
[repo_usd]
usd_root = "${root}/_build/usd-deps/nv-usd/%{config}"
usd_python_root = "${root}/_build/usd-deps/python"
generate_plugin_buildfiles = true
plugin_buildfile_format = "cmake"
generate_root_buildfile = true


[repo_usd.plugin.mvrFileFormat]
plugin_dir = "${root}/src/usd-plugins/fileFormat/mvrFileFormat"
install_root = "${root}/_install/%{platform}/%{config}/mvrFileFormat"
include_dir = "include/mvrFileFormat"
additional_include_dirs = [
    "../../../../_build/usd-deps/nv_usd/%{config}/include/tbb",
    "${root}/src/usd-plugins/fileFormat/mvrFileFormat/assimp/include"
]
public_headers = [
    "api.h"
]
private_headers = [
    "mvrFileFormat.h",
    "mvrParser/tinyxml2.h",
    "mvrParser/Fixture.h",
    "mvrParser/FixtureFactory.h",
    "mvrParser/LayerFactory.h",
    "mvrParser/MVRParser.h",
    "gdtfParser/GdtfParser.h",
    "gdtfParser/ModelSpecification.h",
    "gdtfParser/Device.h"
]
cpp_files = [
    "mvrFileFormat.cpp",
    "mvrParser/Fixture.cpp",
    "mvrParser/FixtureFactory.cpp",
    "mvrParser/LayerFactory.cpp",
    "mvrParser/MVRParser.cpp",
    "mvrParser/tinyxml2.cpp",
    "gdtfParser/GdtfParser.cpp",
]

resource_files = [
    "plugInfo.json"
]

additional_library_dirs = [
    "${root}/src/usd-plugins/fileFormat/mvrFileFormat"
]

additional_static_libs = [
    "assimp",
    "zlibstatic"
]

usd_lib_dependencies = [
    "arch",
    "tf",
    "plug",
    "vt",
    "gf",
    "sdf",
    "js",
    "pcp",
    "usdGeom",
    "usd",
    "usdLux"
]
