[package]
version = "0.3.0"

title = "MF GDTF converter"
description = "Support of GDTF (General Device Type Format) files in USD."
authors = ["Moment Factory","Frederic Lestage"]

readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"
repository = "https://github.com/MomentFactory/Omniverse-MVR-GDTF-converter"

category = "Rendering"
keywords = ["MVR", "GDTF","Audiovisual","Lighting","Fixture"]

preview_image = "data/preview.png"
icon = "data/icon.png"

[[python.module]]
name = "mf.ov.gdtf"

[python.pipapi]
requirements = [
    "unidecode"
]
use_online_index = true
