[core]
# tells kit that we shouldn't hot reload this extension
reloadable = false

# Load at the start, load all schemas with order -100 (with order -1000 the USD libs are loaded)
# this is necessary (as it to set the extension to auto load)
# so that the schemas get loaded into the UsdSchemaRegistry early enough
order = -100

[package]
# all packages should have this information so it is displayed in the UI properly
author = "NVIDIA USD Core Team"
repository = "https://github.com/NVIDIA-Omniverse/kit-sample-usd-schema"
category = "USD"
title = "USD Example Schema"
version = "1.0.0"
description="Kit extension illustrating how to package a schema extension for use in kit."
keywords = ["schema", "usd"]
readme = "docs/README.md"
changelog = "docs/CHANGES.md"
icon = "data/icon.png"

[dependencies]
# depends on core USD libraries being loaded
"omni.usd.libs" = {}

# when an extension is requested to be enabled, kit will load the python modules
# that are specified here in the order they are specified
# we specify two different python modules, the first is the module we create
# this one will register the plugin with USD so it knows in what module to 
# find our schema types
[[python.module]]
name = "omni.example.schema"

# the second extension is the schema python module itself
# this is the module that developers will import to use the schema in Python
[[python.module]]
name = "OmniExampleSchema"

# this tells kit to load these C++ libraries when the extension loads
# (kit will also try to unload them when the extension is unloaded)
# note that this is required to also make loading the schema python module work
# (importing the schema python module will look for the C++ library as a dependency)
# if you don't load the C++ lib here, your PATH / LD_LIBRARY_PATH variables
# should contain the path to your C++ dll otherwise the python module will
# not load properly!
[[native.library]]
path = "OmniExampleSchema/lib/${lib_prefix}omniExampleSchema${lib_ext}"